eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    appname: authentication-service
    instanceId: authentication-service:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: authentication-service
  flyway:
    locations: classpath:db/migration

