server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8090/eureka
      registerWithEureka: false
      fetchRegistry: true
  instance:
    appname: gateway
    instanceId: gateway:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

zuul:
  sensitive-headers: Cookie,Set-Cookie
  strip-prefix: true
  routes:
    notes-service: /notes-service/**
    authentication-service: /authentication-service/**
    template-service: /template-service/**
