package fr.agaspardcilia.msboilerplate.common.security

enum class Permission {
    // TemplateService
    TEMPLATE_HELLO_WORLD,
    TEMPLATE_NOW,

    // AuthenticationService
    AUTHENTICATION_USER_GET,
    AUTHENTICATION_USER_GET_ALL,
    AUTHENTICATION_USER_REGISTER,
    AUTHENTICATION_USER_REQUEST_PWD_RESET,
    AUTHENTICATION_USER_RESET_PWD,
    AUTHENTICATION_USER_CHANGE_PWD,
    AUTHENTICATION_USER_ACTIVATE,
    AUTHENTICATION_USER_GET_SELF,
    AUTHENTICATION_JWT_AUTH,

    // NotesService
    NOTES_GET,
    NOTES_CREATE,
    NOTES_UPDATE,
    NOTES_DELETE,


}
